services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: go-gist
      POSTGRES_PASSWORD: gogist
      POSTGRES_DB: gogist
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      DB_URL: "postgres://go-gist:gogist@db:5432/gogist?sslmode=disable"
    depends_on:
      - db

volumes:
  postgres_data: